#! /bin/bash

rm -r ~/.config/bspwm/
rm -r ~/.config/dunst/ 
rm -r ~/.config/gtk-2.0/ 
rm -r ~/.config/gtk-3.0/ 
rm -r ~/.config/picom/
rm -r ~/.config/polybar/ 
rm -r ~/.config/rofi/ 

killall polybar

cp -r ~/.themes/purain/rofi/ ~/.config/
cp -r ~/.themes/purain/polybar/ ~/.config/
cp -r ~/.themes/purain/gtk-3.0/ ~/.config/
cp -r ~/.themes/purain/gtk-2.0/ ~/.config/
cp -r ~/.themes/purain/bspwm/ ~/.config/
cp -r ~/.themes/purain/picom/ ~/.config/
cp -r ~/.themes/purain/dunst/ ~/.config/
cp -r ~/.themes/purain/kitty ~/.config/

bspc wm -r

