#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 0
bspc config window_gap 12

bspc config normal_border_color "#2e3440"
bspc config active_border_color "#3b4252"
bspc config focused_border_color "#4c566a"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true

sxhkd &
setxkbmap -option grp:alt_shift_toggle us,ru &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
