#!/bin/bash                                                                                                                                                                                                 
                                                                                                      feh --randomize --no-fehbg --bg-fill ~/.themes/walls/gruvbox_walls/

