#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 4
bspc config window_gap 2

bspc config normal_border_color "#2e3440"
bspc config active_border_color "#3b4252"
bspc config focused_border_color "#81A1C1"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a telegram-desktop desktop=^1

bspc config focus_follows_pointer true

sxhkd &
telegram-desktop &
xrandr --output HDMI-1 --mode 1920x1080 --rate 144 &
setxkbmap -option grp:alt_shift_toggle us,ru &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
